---
- name: Basic Ping Test
  hosts: all
  gather_facts: false  # This saves 10-20 seconds!
  tasks:
    - name: Test connection to all hosts
      ping:

    - name: Display success message
      debug:
        msg: "✅ Successfully connected to {{ inventory_hostname }}"
